# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build ARM

on:
  workflow_dispatch:
  repository_dispatch:
    types: [ force-build ]

jobs:
  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 
      uses: actions/setup-python@v2
      run: |
        pyenv local 3.7.8
        python -m venv .venv
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        pip install -r requirements.txt
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Build python extension
      run: python3 setup.py build_ext --inplace 

    - name: Run tests
      run: python -m xmlrunner discover tests/ -o test-reports
